import {
  PatientQueueViewModel,
  TimelineEventViewModel,
  QueueSummaryViewModel,
} from "@/types/ui";

export const INITIAL_SIMULATED_TIME = "14:42";

export const INITIAL_PATIENTS: PatientQueueViewModel[] = [
  {
    patientId: "pat-104",
    displayId: "P-104",
    ageGroup: "Adult",
    complaint: "Minor hand injury",
    clinicianCategory: 4,
    waitingMinutes: 16,
    minutesSinceReview: 8,
    provisionalRank: 1,
    bestPossibleRank: 1,
    worstPossibleRank: 2,
    stabilityPercent: 94,
    confidence: "high",
    reasons: [
      "All triage observations verified within last 10 minutes",
      "No conflicting notes or unacknowledged updates",
    ],
    hasUnacknowledgedUpdate: false,
    hasManualConcern: false,
    evidence: [
      {
        id: "ev-104-1",
        label: "Superficial laceration inspection",
        value: "Clean margin, hemoperfusion intact",
        source: "triage-nurse",
        status: "verified",
        recordedAt: "14:26",
        relativeTime: "16m ago",
      },
      {
        id: "ev-104-2",
        label: "Pain score (VAS)",
        value: "3 / 10 (mild)",
        source: "patient",
        status: "verified",
        recordedAt: "14:34",
        relativeTime: "8m ago",
      },
      {
        id: "ev-104-3",
        label: "Radial pulse check",
        value: "74 bpm, regular",
        source: "triage-nurse",
        status: "verified",
        recordedAt: "14:34",
        relativeTime: "8m ago",
      },
    ],
    uncertainties: [],
    wearable: undefined,
  },
  {
    patientId: "pat-083",
    displayId: "P-083",
    ageGroup: "Adult",
    complaint: "Abdominal discomfort",
    clinicianCategory: 3,
    waitingMinutes: 23,
    minutesSinceReview: 14,
    provisionalRank: 2,
    bestPossibleRank: 2,
    worstPossibleRank: 5,
    stabilityPercent: 64,
    confidence: "medium",
    reasons: [
      "Two records contain conflicting timestamps",
      "Neither entry has been marked as corrected",
    ],
    hasUnacknowledgedUpdate: false,
    hasManualConcern: false,
    evidence: [
      {
        id: "ev-083-1",
        label: "Pain onset timestamp",
        value: "11:30 (Intake form) vs 13:45 (Triage note)",
        source: "triage-nurse",
        status: "conflicting",
        recordedAt: "14:19",
        relativeTime: "23m ago",
      },
      {
        id: "ev-083-2",
        label: "Abdominal palpation",
        value: "Soft, non-rigid, localized left lower quadrant tenderness",
        source: "triage-nurse",
        status: "verified",
        recordedAt: "14:28",
        relativeTime: "14m ago",
      },
      {
        id: "ev-083-3",
        label: "Temperature check",
        value: "37.2°C (afebrile)",
        source: "triage-nurse",
        status: "verified",
        recordedAt: "14:28",
        relativeTime: "14m ago",
      },
    ],
    uncertainties: [
      {
        id: "unc-083-1",
        type: "conflicting",
        label: "Discrepant pain duration",
        explanation:
          "Intake card records symptoms for 3 hours; nursing assessment notes acute onset within 45 minutes.",
        field: "symptomOnset",
        severity: "medium",
        resolutionAction: "Confirm symptom onset duration with patient",
      },
    ],
    nextBestInformation: {
      uncertaintyId: "unc-083-1",
      title: "Clarify symptom onset discrepancy",
      explanation:
        "Resolving whether symptom onset was 45m or 3h ago stabilizes priority bounds between position #2 and #3.",
      currentRange: [2, 5],
      expectedRange: [2, 3],
      estimatedSeconds: 45,
      uncertaintyReductionPercent: 55,
    },
    wearable: undefined,
  },
  {
    patientId: "pat-176",
    displayId: "P-176",
    ageGroup: "Young adult",
    complaint: "Dizziness",
    clinicianCategory: 3,
    waitingMinutes: 19,
    minutesSinceReview: 5,
    provisionalRank: 3,
    bestPossibleRank: 2,
    worstPossibleRank: 4,
    stabilityPercent: 71,
    confidence: "medium",
    reasons: [
      "Wearable detected sudden sensor change accompanied by movement",
      "Signal quality reduced to 42% (evidence used with reduced weight)",
    ],
    hasUnacknowledgedUpdate: false,
    hasManualConcern: false,
    evidence: [
      {
        id: "ev-176-1",
        label: "Sitting blood pressure",
        value: "112 / 72 mmHg",
        source: "triage-nurse",
        status: "verified",
        recordedAt: "14:23",
        relativeTime: "19m ago",
      },
      {
        id: "ev-176-2",
        label: "Photoplethysmography sensor",
        value: "Heart rate fluctuation (88 → 118 bpm with active accelerometer spikes)",
        source: "wearable",
        status: "unverified",
        recordedAt: "14:37",
        relativeTime: "5m ago",
        signalQuality: 42,
      },
    ],
    uncertainties: [
      {
        id: "unc-176-1",
        type: "motion-artifact",
        label: "Ambulatory motion interference",
        explanation:
          "High accelerometer activity coincides with transient heart-rate elevation. Signal quality degraded.",
        field: "continuousVitals",
        severity: "medium",
        resolutionAction: "Obtain stationary manual pulse verification",
      },
    ],
    nextBestInformation: {
      uncertaintyId: "unc-176-1",
      title: "Perform stationary manual pulse check",
      explanation:
        "Verifying whether rate elevation is motion-induced or physiological stabilizes rank between #2 and #3.",
      currentRange: [2, 4],
      expectedRange: [2, 3],
      estimatedSeconds: 30,
      uncertaintyReductionPercent: 50,
    },
    wearable: {
      connected: true,
      mode: "motion-artifact",
      signalQuality: 42,
      completenessPercent: 86,
      motionDetected: true,
      lastReliableReadingAt: "14:35",
      lastReliableReadingLabel: "78 bpm (stable before ambulation)",
      trend: "uncertain",
      evidenceUsage: "reduced",
      heartRate: 114,
      respiratoryRate: 18,
      oxygenSaturation: 98,
      points: [
        { timestamp: "14:25", value: 76 },
        { timestamp: "14:27", value: 78 },
        { timestamp: "14:29", value: 77 },
        { timestamp: "14:31", value: 79 },
        { timestamp: "14:33", value: 78 },
        { timestamp: "14:35", value: 80 },
        { timestamp: "14:37", value: 114 },
        { timestamp: "14:39", value: 108 },
        { timestamp: "14:41", value: 112 },
      ],
    },
  },
  {
    patientId: "pat-219",
    displayId: "P-219",
    ageGroup: "Older adult",
    complaint: "Breathing discomfort",
    clinicianCategory: 3,
    waitingMinutes: 34,
    minutesSinceReview: 31,
    provisionalRank: 4,
    bestPossibleRank: 2,
    worstPossibleRank: 7,
    stabilityPercent: 38,
    confidence: "low",
    reasons: [
      "Latest observation was recorded 31 minutes ago",
      "New nursing update is awaiting acknowledgement",
      "Placement changes substantially when stale evidence is excluded",
    ],
    hasUnacknowledgedUpdate: true,
    hasManualConcern: false,
    evidence: [
      {
        id: "ev-219-1",
        label: "Initial triage SpO2 & Respiratory Rate",
        value: "SpO2 94% on ambient air, RR 22 / min",
        source: "triage-nurse",
        status: "stale",
        recordedAt: "14:08",
        relativeTime: "34m ago",
      },
      {
        id: "ev-219-2",
        label: "Waiting room nursing note",
        value: "Patient requested water; reports slight increased effort when speaking.",
        source: "triage-nurse",
        status: "unverified",
        recordedAt: "14:36",
        relativeTime: "6m ago",
      },
      {
        id: "ev-219-3",
        label: "History of reactive airway",
        value: "Self-administered inhaler 1 hour prior to arrival with minimal relief",
        source: "patient",
        status: "verified",
        recordedAt: "14:08",
        relativeTime: "34m ago",
      },
    ],
    uncertainties: [
      {
        id: "unc-219-1",
        type: "stale",
        label: "Stale respiratory observation",
        explanation:
          "Respiratory rate and oxygen saturation have not been checked for 31 minutes. Placement spans #2–#7 across conservative vs. deteriorating assumptions.",
        field: "respiratoryVitals",
        severity: "high",
        resolutionAction: "Refresh the latest observation",
      },
      {
        id: "unc-219-2",
        type: "unacknowledged",
        label: "Unacknowledged nursing note",
        explanation:
          "Nursing note regarding speech effort entered 6 minutes ago has not been acknowledged by attending staff.",
        field: "nursingUpdate",
        severity: "medium",
        resolutionAction: "Acknowledge waiting room update",
      },
    ],
    nextBestInformation: {
      uncertaintyId: "unc-219-1",
      title: "Refresh the latest observation",
      explanation:
        "The latest vital observation was recorded 31 minutes ago. Clarifying current SpO2 and respiratory rate will shrink the placement range from #2–#7 to #3–#4.",
      currentRange: [2, 7],
      expectedRange: [3, 4],
      estimatedSeconds: 50,
      uncertaintyReductionPercent: 72,
    },
    wearable: undefined,
  },
  {
    patientId: "pat-301",
    displayId: "P-301",
    ageGroup: "Adult",
    complaint: "Persistent weakness",
    clinicianCategory: 4,
    waitingMinutes: 28,
    minutesSinceReview: 18,
    provisionalRank: 5,
    bestPossibleRank: 4,
    worstPossibleRank: 6,
    stabilityPercent: 62,
    confidence: "medium",
    reasons: [
      "Wearable was previously connected but currently disconnected",
      "No reliable reading received for four simulated minutes",
      "Continuous physiological evidence is becoming stale",
    ],
    hasUnacknowledgedUpdate: false,
    hasManualConcern: false,
    evidence: [
      {
        id: "ev-301-1",
        label: "Capillary blood glucose",
        value: "5.8 mmol/L (normal range)",
        source: "triage-nurse",
        status: "verified",
        recordedAt: "14:14",
        relativeTime: "28m ago",
      },
      {
        id: "ev-301-2",
        label: "Last recorded telemetry stream",
        value: "Heart rate 72 bpm, SpO2 98% (signal lost at 14:38)",
        source: "wearable",
        status: "stale",
        recordedAt: "14:38",
        relativeTime: "4m ago",
      },
    ],
    uncertainties: [
      {
        id: "unc-301-1",
        type: "sensor-dropout",
        label: "Telemetry stream disconnected",
        explanation:
          "Monitor lost telemetry connection 4 minutes ago. Previously continuous evidence is excluded until reconnected or manually verified.",
        field: "wearableStream",
        severity: "medium",
        resolutionAction: "Re-seat pulse oximeter probe or verify vitals manually",
      },
    ],
    nextBestInformation: {
      uncertaintyId: "unc-301-1",
      title: "Re-seat wearable probe or conduct manual check",
      explanation:
        "Restoring continuous telemetry or confirming manual pulse narrows uncertainty bounds from #4–#6 to #5.",
      currentRange: [4, 6],
      expectedRange: [5, 5],
      estimatedSeconds: 30,
      uncertaintyReductionPercent: 60,
    },
    wearable: {
      connected: false,
      mode: "disconnected",
      signalQuality: 0,
      completenessPercent: 54,
      motionDetected: false,
      lastReliableReadingAt: "14:38",
      lastReliableReadingLabel: "72 bpm (4 minutes ago)",
      trend: "uncertain",
      evidenceUsage: "excluded",
      heartRate: undefined,
      respiratoryRate: undefined,
      oxygenSaturation: undefined,
      points: [
        { timestamp: "14:26", value: 74 },
        { timestamp: "14:28", value: 72 },
        { timestamp: "14:30", value: 73 },
        { timestamp: "14:32", value: 71 },
        { timestamp: "14:34", value: 72 },
        { timestamp: "14:36", value: 73 },
        { timestamp: "14:38", value: 72 },
      ],
    },
  },
  {
    patientId: "pat-412",
    displayId: "P-412",
    ageGroup: "Adult",
    complaint: "Headache",
    clinicianCategory: 4,
    waitingMinutes: 12,
    minutesSinceReview: 3,
    provisionalRank: 6,
    bestPossibleRank: 5,
    worstPossibleRank: 6,
    stabilityPercent: 88,
    confidence: "high",
    reasons: [
      "New nursing note has not been acknowledged",
      "Observations otherwise recent and within expected parameters",
    ],
    hasUnacknowledgedUpdate: true,
    hasManualConcern: false,
    evidence: [
      {
        id: "ev-412-1",
        label: "Visual analogue pain scale",
        value: "5 / 10, frontal tension pattern",
        source: "patient",
        status: "verified",
        recordedAt: "14:30",
        relativeTime: "12m ago",
      },
      {
        id: "ev-412-2",
        label: "Neurological screen",
        value: "Pupils equal, round, reactive to light; no focal deficit",
        source: "triage-nurse",
        status: "verified",
        recordedAt: "14:30",
        relativeTime: "12m ago",
      },
      {
        id: "ev-412-3",
        label: "Waiting room comfort note",
        value: "Offered dim light seating; declined oral paracetamol",
        source: "triage-nurse",
        status: "unverified",
        recordedAt: "14:39",
        relativeTime: "3m ago",
      },
    ],
    uncertainties: [
      {
        id: "unc-412-1",
        type: "unacknowledged",
        label: "Unacknowledged comfort note",
        explanation: "Nursing entry at 14:39 awaiting clinician acknowledgement.",
        field: "nursingComfortNote",
        severity: "low",
        resolutionAction: "Acknowledge note entry",
      },
    ],
    nextBestInformation: {
      uncertaintyId: "unc-412-1",
      title: "Acknowledge recent nursing note",
      explanation:
        "Simple acknowledgment will clear the open review flag and confirm queue stability.",
      currentRange: [5, 6],
      expectedRange: [6, 6],
      estimatedSeconds: 15,
      uncertaintyReductionPercent: 40,
    },
    wearable: undefined,
  },
];

export const INITIAL_TIMELINE_EVENTS: TimelineEventViewModel[] = [
  {
    id: "evt-init-1",
    patientId: "pat-219",
    timestamp: "14:08",
    relativeTime: "34m ago",
    type: "arrival",
    actor: "Triage Nurse Evans",
    title: "Patient Intake & Formal Triage",
    description: "Assigned staff category 3 (Urgent). Breathing discomfort.",
  },
  {
    id: "evt-init-2",
    patientId: "pat-301",
    timestamp: "14:14",
    relativeTime: "28m ago",
    type: "arrival",
    actor: "Triage Nurse Evans",
    title: "Patient Intake & Formal Triage",
    description: "Assigned staff category 4. Telemetry monitor affixed.",
  },
  {
    id: "evt-init-3",
    patientId: "pat-083",
    timestamp: "14:19",
    relativeTime: "23m ago",
    type: "arrival",
    actor: "Triage Nurse Wong",
    title: "Patient Intake & Formal Triage",
    description: "Assigned staff category 3. Abdominal tenderness noted.",
  },
  {
    id: "evt-init-4",
    patientId: "pat-176",
    timestamp: "14:23",
    relativeTime: "19m ago",
    type: "wearable-connected",
    actor: "Nurse Wong",
    title: "Continuous Monitor Connected",
    description: "Photoplethysmography sensor synchronized to telemetry.",
  },
  {
    id: "evt-init-5",
    patientId: "pat-104",
    timestamp: "14:26",
    relativeTime: "16m ago",
    type: "arrival",
    actor: "Triage Nurse Evans",
    title: "Patient Intake & Formal Triage",
    description: "Assigned staff category 4. Superficial laceration.",
  },
  {
    id: "evt-init-6",
    patientId: "pat-412",
    timestamp: "14:30",
    relativeTime: "12m ago",
    type: "arrival",
    actor: "Triage Nurse Wong",
    title: "Patient Intake & Formal Triage",
    description: "Assigned staff category 4. Frontal tension headache.",
  },
  {
    id: "evt-init-7",
    patientId: "pat-219",
    timestamp: "14:36",
    relativeTime: "6m ago",
    type: "information-added",
    actor: "Floor Nurse Miller",
    title: "Waiting Area Observation Added",
    description: "Patient noted to have increased conversational effort.",
  },
  {
    id: "evt-init-8",
    patientId: "pat-301",
    timestamp: "14:38",
    relativeTime: "4m ago",
    type: "wearable-disconnected",
    actor: "Telemetry System",
    title: "Wearable Telemetry Disconnected",
    description: "Signal lost. No reliable readings for 4 minutes.",
  },
  {
    id: "evt-init-9",
    patientId: "pat-412",
    timestamp: "14:39",
    relativeTime: "3m ago",
    type: "information-added",
    actor: "Floor Nurse Miller",
    title: "Comfort Update Logged",
    description: "Offered dim light seating; declined oral medication.",
  },
];

export const INITIAL_SUMMARY: QueueSummaryViewModel = {
  queueConfidence: 68,
  unstableCount: 2, // P-219 (low), P-083/P-176 (medium) - unstable definition: confidence low or medium with wide range
  unresolvedUpdateCount: 2, // P-219, P-412
  totalWaiting: 6,
  simulatedTime: INITIAL_SIMULATED_TIME,
};
